GW2Treasures/gw2api

tests/V2/BuildEndpointTest.php
Adds tests for BuildEndpoint. (See #1)
=> Add tests for BuildEndpoint

src/V2/Pagination/IPaginatedEndpoint.php, tests/PaginatedEndpointTest.php, tests/Stubs/PaginatedEndpointStub.php
Adds tests for PaginatedEndpoint. (see #1)
=> Add PaginatedEndpoint tests

src/V2/Localization/LocalizedEndpointProxy.php, tests/LocalizedEndpointTest.php, tests/Stubs/LocalizedEndpointStub.php
Adds tests for LocalizedEndpoint and fixes all discovered bugs. (See #1)
=> Add LocalizedEndpoint tests

tests/AuthenticatedEndpointTest.php, tests/Stubs/AuthenticatedEndpointStub.php
Adds tests for AuthenticatedEndpoint (see #1)
=> Add AuthenticatedEndpoint tests

tests/BulkEndpointTest.php, tests/Stubs/BulkEndpointStub.php
Adds tests for BulkEndpoint (see #1)
=> Add BulkEndpoint tests

.travis.yml, composer.json, composer.lock
Use coveralls.io to report test coverage from travis builds. (see #1)
=> Add test coverage to travis

tests/V2/RecipeEndpointTest.php
Adds tests for RecipeEndpoint (see #1)
=> Add RecipeEndpoint tests

tests/V2/CommerceEndpointTest.php, tests/V2/CommerceTransactionEndpointTest.php
Adds tests for CommerceEndpoint. (See #1)
=> Add CommerceEndpoint tests

src/V2/ApiHandler.php, src/V2/Authentication/AuthenticationHandler.php, tests/ApiHandlerTest.php, tests/AuthenticatedEndpointTest.php
Adds tests for ApiHandler. (See #1)
=> Add ApiHandler tests

.travis.yml, README.md, composer.json, composer.lock
Coveralls isn't reporting the coverage correctly and was down for the last few days. Lets test [codecov.io](https://codecov.io/).
=> Replace coveralls with codecov.io

README.md, src/GW2Api.php, src/V2/Endpoint/Specialization/SpecializationEndpoint.php, tests/V2/SpecializationEndpointTest.php
This adds support for `/v2/specializations` and adds tests. (See #25)
=> Add SpecializationEndpoint

src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/DyeEndpoint.php, tests/V2/AccountDyeEndpointTest.php
Adds /v2/account/dyes endpoint. (see #27)
=> Add /v2/account/dyes endpoint

src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/SkinEndpoint.php, tests/V2/AccountSkinEndpointTest.php
Adds /v2/account/skins endpoint. (see #27)
=> Add /v2/account/skins endpoint

src/GW2Api.php, src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/WalletEndpoint.php, src/V2/Endpoint/Currency/CurrencyEndpoint.php, tests/V2/AccountWalletEndpointTest.php, tests/V2/CurrencyEndpointTest.php
Adds /v2/account/wallet and /v2/currencies Endpoints. (see #27)
=> Add /v2/account/wallet and /v2/currencies Endpoints

README.md, src/GW2Api.php, src/V2/Endpoint/Traits/TraitEndpoint.php, tests/V2/TraitEndpointTest.php
Adds /v2/traits endpoint. (see #25)
=> Add /v2/traits endpoint

README.md, src/GW2Api.php, src/V2/Authentication/AuthenticatedEndpoint.php, src/V2/Endpoint/Pvp/GameEndpoint.php, src/V2/Endpoint/Pvp/PvpEndpoint.php, src/V2/Endpoint/Pvp/StatsEndpoint.php, tests/V2/PvpEndpointTest.php, tests/V2/PvpGameEndpointTest.php, tests/V2/PvpStatsEndpointTest.php
Adds /v2/pvp/games and /v2/pvp/stats Endpoints. (see #31)
=> Add /v2/pvp/games and /v2/pvp/stats endpoints

README.md, src/V2/Endpoint/Character/CharacterEndpoint.php, src/V2/Endpoint/Character/SpecializationEndpoint.php, tests/V2/CharacterSpecializationEndpointTest.php
Adds /v2/characters/:id/specializations endpoint. (see #31)
=> Add /v2/characters/:id/specializations endpoint

README.md, src/GW2Api.php, src/V2/Endpoint/WvW/ObjectiveEndpoint.php, src/V2/Endpoint/WvW/WvWEndpoint.php, tests/V2/WvWEndpointTest.php
Adds the /v2/wvw/objectives endpoint.
=> Add /v2/wvw/objectives endpoint

README.md, src/V2/Endpoint/WvW/MatchEndpoint.php, src/V2/Endpoint/WvW/WvWEndpoint.php, tests/V2/WvWEndpointTest.php
Adds /v2/wvw/matches (see #39).
=> Add /v2/wvw/matches Endpoint

README.md, src/GW2Api.php, src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/MiniEndpoint.php, src/V2/Endpoint/Mini/MiniEndpoint.php, tests/V2/AccountMiniEndpointTest.php, tests/V2/MiniEndpointTest.php
Adds /v2/minis and /v2/account/minis (see #40).
=> Add miniature endpoints

README.md, src/GW2Api.php, src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/AchievementEndpoint.php, src/V2/Endpoint/Achievement/AchievementEndpoint.php, tests/V2/AccountAchievementEndpointTest.php, tests/V2/AchievementEndpointTest.php, tests/V2/MiniEndpointTest.php
Adds /v2/achievements and /v2/account/achievements (see #38).
=> Add achievement endpoints

README.md, src/GW2Api.php, src/V2/Endpoint/Emblem/EmblemEndpoint.php, src/V2/Endpoint/Emblem/LayerEndpoint.php, tests/V2/EmblemEndpointTest.php
Adds /v2/emblem and /v2/emblem/:type endpoints.
=> Add /v2/emblem endpoint

README.md, src/V2/Endpoint/Achievement/AchievementEndpoint.php, src/V2/Endpoint/Achievement/DailyEndpoint.php, tests/V2/AchievementEndpointTest.php
Adds /v2/achievements/daily endpoint (see #38).
=> Add daily achievement endpoint

README.md, src/V2/Endpoint/Achievement/AchievementEndpoint.php, src/V2/Endpoint/Achievement/CategoryEndpoint.php, src/V2/Endpoint/Achievement/GroupEndpoint.php, tests/V2/AchievementEndpointTest.php
Adds `/v2/achievements/categories` and `/v2/achievements/groups` endpoints (see #38).
=> Add achievement categories and groups endpoints

README.md, src/V2/Endpoint/Character/CharacterEndpoint.php, src/V2/Endpoint/Character/RecipeEndpoint.php, tests/V2/CharacterEndpointTest.php
Adds `/v2/characters/:id/recipes` endpoint (see #47).
=> Add character recipes endpoint

README.md, src/GW2Api.php, src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/UpgradeEndpoint.php, tests/V2/GuildEndpointTest.php
Add `/v2/guild/upgrades` endpoint (see #48).
=> Add guild upgrades endpoint

README.md, src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/PermissionEndpoint.php, tests/V2/GuildEndpointTest.php
Adds /v2/guilds/permissions endpoint (see #54).
=> Add guild permissions endpoint

README.md, src/GW2Api.php, src/V2/Endpoint/Guild/Exception/GuildException.php, src/V2/Endpoint/Guild/Exception/GuildLeaderRequiredException.php, src/V2/Endpoint/Guild/Exception/MembershipRequiredException.php, src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/IRestrictedGuildEndpoint.php, src/V2/Endpoint/Guild/MemberEndpoint.php, src/V2/Endpoint/Guild/RankEndpoint.php, src/V2/Endpoint/Guild/RestrictedGuildHandler.php, tests/V2/GuildEndpointTest.php
Adds /v2/guild/:id/members and /v2/guild/:id/ranks (see #55)
=> Add guild ranks and members endpoints

README.md, src/GW2Api.php, src/V2/Endpoint/Skill/SkillEndpoint.php, tests/V2/SkillEndpointTest.php
Adds /v2/skills endpoint (see #58).
=> Adds /v2/skills endpoint

README.md, src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/InventoryEndpoint.php, tests/V2/AccountEndpointTest.php
Adds /v2/account/inventory endpoint (see #62).
=> Add /v2/account/inventory endpoint

README.md, src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/LogEndpoint.php, tests/V2/GuildEndpointTest.php
Add acces to /v2/guild/:id/log endpoint (see #61)
=> add /v2/guild/:id/log endpoint

README.md, src/V2/Endpoint/WvW/MatchEndpoint.php, tests/V2/WvWEndpointTest.php
=> Add method to get the current match of a world

src/V2/Endpoint/Pvp/AmuletEndpoint.php, src/V2/Endpoint/Pvp/PvpEndpoint.php, tests/V2/PvpEndpointTest.php
This will fix the issue 71 ( https://github.com/GW2Treasures/gw2api/issues/71 ) 
The feature is tested :)
=> issue #71 add the /v2/pvp/amulets endpoint

src/GW2Api.php, src/V2/Endpoint/Legend/LegendEndpoint.php, src/V2/Endpoint/Pet/PetEndpoint.php, tests/V2/AchievementEndpointTest.php, tests/V2/LegendEndpointTest.php, tests/V2/MiniEndpointTest.php, tests/V2/PetEndpointTest.php
Fix the issue 70 ( https://github.com/GW2Treasures/gw2api/issues/70 ) 
+ minor fix to AchievementEndpointTest & MiniEndpointTest class names  ;) ( they were swapped )
=> Add /v2/pets and /v2/legends endpoints

src/V2/Endpoint/Pvp/PvpEndpoint.php, src/V2/Endpoint/Pvp/StandingEndpoint.php, tests/V2/PvpEndpointTest.php
fix the issue 65 ( https://github.com/GW2Treasures/gw2api/issues/65 )
=> fix issue #65 add /v2/pvp/standings endpoint

src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/TeamEndpoint.php, tests/V2/GuildEndpointTest.php
fix issue 64 ( https://github.com/GW2Treasures/gw2api/issues/64 )
=> issue #64 : add /v2/guild/:id/teams endpoint

src/V2/Endpoint/Pvp/PvpEndpoint.php, src/V2/Endpoint/Pvp/SeasonEndpoint.php, tests/V2/PvpEndpointTest.php
fix issue 63 ( https://github.com/GW2Treasures/gw2api/issues/63 )
=> issue #63 : add /v2/pvp/seasons endpoint

src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/StashEndpoint.php, src/V2/Endpoint/Guild/TreasuryEndpoint.php, tests/V2/GuildEndpointTest.php
fix the issue 59 ( https://github.com/GW2Treasures/gw2api/issues/59 )
=> issue #59 : add /v2/guild/:id/stash and /v2/guild/:id/treasury endpoints

src/V2/Endpoint/Achievement/AchievementEndpoint.php, src/V2/Endpoint/Achievement/DailyTomorrowEndpoint.php, tests/V2/AchievementEndpointTest.php
Adds the `/v2/achievements/daily/tomorrow` endpoint.
=> Add /v2/achievements/daily/tomorrow endpoint

src/V2/Endpoint/Character/CharacterEndpoint.php, src/V2/Endpoint/Continent/ContinentEndpoint.php, src/V2/Endpoint/Continent/FloorEndpoint.php, src/V2/Endpoint/Continent/MapEndpoint.php, src/V2/Endpoint/Continent/PoiEndpoint.php, src/V2/Endpoint/Continent/RegionEndpoint.php, src/V2/Endpoint/Continent/SectorEndpoint.php, src/V2/Endpoint/Continent/TaskEndpoint.php, src/V2/Endpoint/Guild/Authenticated/LogEndpoint.php, src/V2/Endpoint/Guild/GuildEndpoint.php, src/V2/Endpoint/Guild/PermissionEndpoint.php, src/V2/Endpoint/Guild/UpgradeEndpoint.php, tests/V2/CharacterEndpointTest.php, tests/V2/CharacterEquipmentEndpointTest.php, tests/V2/CharacterInventoryEndpointTest.php, tests/V2/CharacterSpecializationEndpointTest.php, tests/V2/ContinentEndpointTest.php, tests/V2/GuildEndpointTest.php
Rename all methods of `endpoint/:id/something` endpoints to `endpoint->somethingOf($id)`.
=> Rename all methods of endpoint/:id/something endpoints

src/GW2Api.php, src/V2/Endpoint/Profession/ProfessionEndpoint.php, src/V2/Endpoint/Pvp/StatsEndpoint.php, tests/V2/ProfessionEndpointTest.php
Adds /v2/professions endpoint. see #85
=> Add /v2/professions endpoint

README.md
=> Add missing documentation for new endpoints

src/GW2Api.php, src/V2/Endpoint/Account/AccountEndpoint.php, src/V2/Endpoint/Account/DungeonEndpoint.php, src/V2/Endpoint/Account/Home/CatEndpoint.php, src/V2/Endpoint/Account/Home/HomeEndpoint.php, src/V2/Endpoint/Account/Home/NodeEndpoint.php, src/V2/Endpoint/Account/RaidEndpoint.php, src/V2/Endpoint/Dungeon/DungeonEndpoint.php, src/V2/Endpoint/Race/RaceEndpoint.php, src/V2/Endpoint/Raid/RaidEndpoint.php, src/V2/Endpoint/WvW/UpgradeEndpoint.php, src/V2/Endpoint/WvW/WvWEndpoint.php, tests/V2/AccountEndpointTest.php, tests/V2/DungeonEndpointTest.php, tests/V2/RaceEndpointTest.php, tests/V2/RaidEndpointTest.php, tests/V2/WvWEndpointTest.php
=> Add new endpoints

.github/workflows/ci.yml
=> Report coverage in PRs

src/V2/ApiHandler.php, src/V2/Endpoint.php, src/V2/Localization/LocalizationHandler.php, tests/ApiHandlerTest.php
=> Return $response from ApiHandler

src/GW2Api.php
=> Replace deprecated getClass with getType
